# site settings
title: My Profile
subtitle: by Ruby
email: elysian0121@gmail.com
description: I am an English teacher working at a private high school in Tamsui, Taiwan.<br /> and have a passion for teaching.
baseurl: "/main" # the subpath of your site, e.g. /blog
url: "https://elysian0121.github.io/main" # the base hostname & protocol for your site
author:
street_address: 26 Zhenli Street
city: NTPC
state: Taiwan
zip_code: 251024
country: Taiwan
phone: (02) 26203850

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://www.tksh.ntpc.edu.tw/
  GitLab: https://www.tksh.ntpc.edu.tw/
  Google-Plus: https://www.tksh.ntpc.edu.tw/
  Instagram: https://www.tksh.ntpc.edu.tw/
  LinkedIn: https://www.tksh.ntpc.edu.tw/
  Twitter: https://www.tksh.ntpc.edu.tw/
  Facebook: https://www.facebook.com/p/%E6%96%B0%E5%8C%97%E5%B8%82%E7%A7%81%E7%AB%8B%E6%B7%A1%E6%B1%9F%E9%AB%98%E7%B4%9A%E4%B8%AD%E5%AD%B8-100064178763805/
  Slack: https://www.tksh.ntpc.edu.tw/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
theme: jekyll-theme-primer
